name: 'Require PR Action'
description: Use this action to revert commits on a branch that were pushed without a PR. Can limit to only certain users
inputs:
  branch:
    description: 'Branch to monitor for commits pushed without a PR'
    required: true
  users:
    description: 'Comma separated list of users to deny to push without a PR. By default this applies to all users'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      shell: bash
      with:
        ref: ${{ github.event.push.ref }}
        fetch-depth: 2
    - name: Determine if push from PR
      uses: actions/github-script@v7
      id: determine_if_pr
      shell: bash
      with:
        script: |
          const users = '${{ inputs.users }}'.split(',');
          if (!users.includes(context.actor)) {
            return true;
          }
          const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
          if (result.data[0] && result.data[0].number > 0) { 
            return true;
          } else { 
            return false; 
          }
        result-encoding: string
    - name: Undo direct push
      if: ${{ steps.determine_if_pr.outputs.result == 'false' }}
      shell: bash
      run: |
        git reset --hard HEAD~1
        git push -f origin ${{ inputs.branch }}